### ISSUE TITLE
Project abandonned ?

### ISSUE THREAD

**Issue by jonathangreco** [charliesbox/react-native-media-controls#11]
Hi,

I was really interested about this project that seemed to be working as I wanted.
Since I installed it I encountered some issues that make it unusable for my app.

- If the video is under 5 seconds, the player wont start, plus, if it's a recorded video, it crashes. I suspect this comes from the fade that is not really well made, too long, and not configurable.

- The fullscreen icon, is not working, because no implementation exist yet, so this icon is just for the style but it's not suitable for app that requires to be perfect visually speaking.

Is this project still maintained ? If not could you update your readme to warn people that this product is delivered as user's own risk because no further debug or fix will be done.

**Comment by andrewhamill** [comment]
I would be happy to take this on.

**Comment by charliesbox** [comment]
I've been a little bit disconnected from react native world. But this is not abandoned at all!

I'm happy to see that it is pretty popular. 

Time to update the package :)
