### ISSUE TITLE
Packaging failure

### ISSUE THREAD

**Issue by hlh6512500** [charliesbox/react-native-media-controls#8]
`TransformError: C:\..........\node_modules\react-native-media-controls\lib\index.js: Couldn't find preset "flow" relative to directory "C:\..........\node_modules\\react-native-media-controls"

:app:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'cmd'' finished with non-zero exit value 1`

**Comment by charliesbox** [comment]
oh wow, lemme check

**Comment by charliesbox** [comment]
Already tested and haven't found an issue. Also, I published a new version without the src code and *rc files, just the transpiled version

Let me know if that did the trick for you

**Comment by charliesbox** [comment]
Closing inactive issue
